# Generated by Django 2.0.7 on 2019-10-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmf', models.CharField(max_length=8)),
                ('client_name', models.CharField(max_length=120)),
                ('device_name', models.CharField(max_length=120)),
                ('device_ip', models.CharField(max_length=15)),
                ('cdp_scrape', models.TextField(blank=True, null=True)),
                ('interface_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
