# Generated by Django 2.0.7 on 2019-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0002_cdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_Inter_Reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmf', models.CharField(max_length=8)),
                ('client_name', models.CharField(max_length=120)),
                ('directory', models.CharField(max_length=220)),
                ('separator', models.CharField(max_length=1)),
                ('cdp_scrape', models.TextField(blank=True, null=True)),
                ('interface_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
