# Generated by Django 2.0.7 on 2019-10-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0003_phone_inter_reset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone_Inter_Reset',
        ),
    ]
